# Generated by Django 4.2.21 on 2025-06-02 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_log", "0004_alter_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
